# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d656e044f994c1acfdab240b10097f640d83316c73db4f446a79810779bd25aabd58d76274e218dfcc2ae099e8caa26e707ea845cfa29ad15f823e92df5cfed1

test:
  secret_key_base: b481cd089e8bf4d8033638e0dbc5217081926888f7691a1bf41366fff43bb9aa363b8cd4aaf4fdd43e2816d26efc5cebcf755a51cda8e36b36724c376304b64a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
